import { builder } from "../builder";
import { requireUser, rateLimited, badRequest, notFound } from "../errors";
import { askAdvisor, generateAdvisorTitle } from "@/lib/ai/advisor";
import {
  listAdvisorConversations,
  getAdvisorConversation,
  getAdvisorHistory,
  createAdvisorConversation,
  appendAdvisorTurns,
  deleteAdvisorConversation,
  type AdvisorTurnInput,
} from "@/lib/db/advisor";
import { recordAiUsage, countAdvisorTurnsSince, type AiUsageInput } from "@/lib/db/ai-usage";
import { rateLimit, MINUTE, HOUR, DAY } from "@/lib/rate-limit";

const MAX_MESSAGE_CHARS = 2000;
const MAX_HISTORY_TURNS = 20; // prior turns fed to the model — bounds tokens/cost
// Durable per-user daily cap on advisor messages, to curb abuse/cost. Counted
// from the DB (not the in-memory limiter) so it survives restarts, over a
// rolling 24h window.
const DAILY_MESSAGE_LIMIT = 50;

// Ask the budget advisor a question within a persisted conversation. History is
// loaded from the DB (never trusted from the client), the answer is generated by
// a read-only, user-scoped tool loop (lib/ai/advisor), and both turns are saved.
// Returns { answer, sources, conversationId } — the id lets a brand-new chat keep
// appending. Rate-limited per user.
builder.mutationField("askAdvisor", (t) =>
  t.field({
    type: "JSON",
    args: {
      message: t.arg.string({ required: true }),
      conversationId: t.arg.string({ required: false }),
    },
    resolve: async (_root, args, ctx) => {
      const userId = requireUser(ctx);

      const limit = rateLimit(`ai:advisor:${userId}`, [
        { limit: 10, windowMs: MINUTE },
        { limit: 120, windowMs: HOUR },
      ]);
      if (!limit.ok) rateLimited(limit.retryAfterSec);

      const message = args.message.trim();
      if (!message) badRequest("Ask a question about your finances.");
      if (message.length > MAX_MESSAGE_CHARS) {
        badRequest(`Keep your question under ${MAX_MESSAGE_CHARS} characters.`);
      }

      // Durable daily cap: bounds cost/abuse even across process restarts.
      const dailyCount = await countAdvisorTurnsSince(userId, new Date(Date.now() - DAY));
      if (dailyCount >= DAILY_MESSAGE_LIMIT) {
        rateLimited(
          DAY / 1000,
          `You've reached the daily limit of ${DAILY_MESSAGE_LIMIT} advisor messages. Please try again tomorrow.`,
        );
      }

      const conversationId = args.conversationId ?? null;

      // Load prior turns from the DB (ownership-checked). A missing/foreign id is
      // a 404 — the model never sees another user's conversation.
      let history: { role: "user" | "assistant"; content: string }[] = [];
      if (conversationId) {
        const h = await getAdvisorHistory(userId, conversationId, MAX_HISTORY_TURNS);
        if (h === null) notFound("Conversation not found.");
        history = h;
      }

      const { answer, sources, usage, model } = await askAdvisor(userId, message, history);

      // Persist only after a successful answer, so a failed call leaves no
      // empty conversation behind.
      const turns: AdvisorTurnInput[] = [
        { role: "user", content: message },
        { role: "assistant", content: answer, sources },
      ];

      const usageEvents: AiUsageInput[] = [];
      let convId = conversationId;
      if (convId) {
        const ok = await appendAdvisorTurns(userId, convId, turns);
        if (!ok) notFound("Conversation not found.");
      } else {
        const { title, usage: titleUsage, model: titleModel } = await generateAdvisorTitle(message);
        convId = await createAdvisorConversation(userId, title, turns);
        if (titleUsage) {
          usageEvents.push({ userId, kind: "advisor_title", model: titleModel, usage: titleUsage, conversationId: convId });
        }
      }

      // Track token usage + cost for this turn (best-effort; never blocks the reply).
      usageEvents.push({ userId, kind: "advisor", model, usage, conversationId: convId });
      await recordAiUsage(usageEvents);

      return { answer, sources, conversationId: convId };
    },
  }),
);

// Sidebar list of the user's saved chats (most-recently-active first).
builder.queryField("advisorConversations", (t) =>
  t.field({
    type: "JSON",
    resolve: (_root, _args, ctx) => listAdvisorConversations(requireUser(ctx)),
  }),
);

// Full thread for reopening a past chat. 404 if not the user's.
builder.queryField("advisorConversation", (t) =>
  t.field({
    type: "JSON",
    args: { id: t.arg.string({ required: true }) },
    resolve: async (_root, args, ctx) => {
      const convo = await getAdvisorConversation(requireUser(ctx), args.id);
      if (!convo) notFound("Conversation not found.");
      return convo;
    },
  }),
);

// Delete a saved chat (messages cascade).
builder.mutationField("deleteAdvisorConversation", (t) =>
  t.field({
    type: "JSON",
    args: { id: t.arg.string({ required: true }) },
    resolve: async (_root, args, ctx) => {
      const ok = await deleteAdvisorConversation(requireUser(ctx), args.id);
      return { ok };
    },
  }),
);
